insert into public."PROMPT_categories" (id, code)
values
  (1, 'Business'),
  (2, 'Coding'),
  (3, 'Education'),
  (4, 'ImageGeneration'),
  (5, 'Influencer'),
  (6, 'Job'),
  (7, 'Marketing'),
  (8, 'Politics'),
  (9, 'Productivity'),
  (10, 'School'),
  (11, 'Seo'),
  (12, 'University'),
  (13, 'YouTube')
on conflict (code) do update set code = excluded.code;

insert into public."PROMPT_main_categories" (id, code)
values
  (1, 'Business'),
  (2, 'Coding'),
  (3, 'ImageGeneration'),
  (4, 'Influencer'),
  (5, 'Job'),
  (6, 'Politics'),
  (7, 'School'),
  (8, 'University')
on conflict (code) do update set code = excluded.code;

insert into public."PROMPT_platforms" (id, name)
values
  (1, 'Amazon Q'),
  (2, 'Character.AI'),
  (3, 'ChatGPT'),
  (4, 'Claude'),
  (5, 'DeepSeek'),
  (6, 'Gemini'),
  (7, 'GitHub Copilot'),
  (8, 'Grok'),
  (9, 'Instagram'),
  (10, 'Jasper'),
  (11, 'LinkedIn'),
  (12, 'LMS'),
  (13, 'Meta AI'),
  (14, 'Microsoft Copilot'),
  (15, 'Midjourney'),
  (16, 'Mistral Le Chat'),
  (17, 'Notion AI'),
  (18, 'Perplexity'),
  (19, 'Phind'),
  (20, 'Pi'),
  (21, 'Poe'),
  (22, 'Public Briefing'),
  (23, 'Qwen'),
  (24, 'Replit Agent'),
  (25, 'You.com'),
  (26, 'YouTube')
on conflict (name) do update set name = excluded.name;

insert into public."PROMPT_tones" (id, code)
values
  (1, 'Analytical'),
  (2, 'Creative'),
  (3, 'Friendly'),
  (4, 'Persuasive'),
  (5, 'Professional')
on conflict (code) do update set code = excluded.code;

insert into public."PROMPT_lengths" (id, code)
values
  (1, 'Long'),
  (2, 'Medium'),
  (3, 'Short')
on conflict (code) do update set code = excluded.code;

insert into public."PROMPT_output_formats" (id, code)
values
  (1, 'BulletPoints'),
  (2, 'Json'),
  (3, 'Narrative'),
  (4, 'StepByStep'),
  (5, 'Table')
on conflict (code) do update set code = excluded.code;

insert into public."PROMPT_complexity_levels" (id, code)
values
  (1, 'Advanced'),
  (2, 'Basic'),
  (3, 'Expert'),
  (4, 'Intermediate')
on conflict (code) do update set code = excluded.code;

insert into public."PROMPT_subcategories" (id, category_id, name_de, name_en)
values
  (1, 1, 'Change', 'Change'),
  (2, 1, 'Kommunikation', 'Communication'),
  (3, 1, 'Operations', 'Operations'),
  (4, 1, 'Partnerschaften', 'Partnerships'),
  (5, 1, 'Planung', 'Planning'),
  (6, 1, 'Pricing', 'Pricing'),
  (7, 1, 'Reporting', 'Reporting'),
  (8, 1, 'Risiko', 'Risk'),
  (9, 1, 'Strategie', 'Strategy'),
  (10, 1, 'Vertrieb', 'Sales'),
  (11, 2, 'API Design', 'API design'),
  (12, 2, 'Code Review', 'Code review'),
  (13, 2, 'Datenmodell', 'Data model'),
  (14, 2, 'Debugging', 'Debugging'),
  (15, 2, 'DevOps', 'DevOps'),
  (16, 2, 'Microservices', 'Microservices'),
  (17, 2, 'Performance', 'Performance'),
  (18, 2, 'Refactoring', 'Refactoring'),
  (19, 2, 'Security', 'Security'),
  (20, 2, 'Testing', 'Testing'),
  (21, 3, 'Assessment', 'Assessment'),
  (22, 3, 'Blended Learning', 'Blended learning'),
  (23, 3, 'Curriculum', 'Curriculum'),
  (24, 3, 'Diagnostik', 'Diagnostics'),
  (25, 3, 'Didaktik', 'Didactics'),
  (26, 3, 'Feedback', 'Feedback'),
  (27, 3, 'Kollaboration', 'Collaboration'),
  (28, 3, 'Kompetenzen', 'Competencies'),
  (29, 3, 'Personalisierung', 'Personalization'),
  (30, 3, 'Unterrichtsdesign', 'Lesson design'),
  (31, 4, 'Architektur', 'Architecture'),
  (32, 4, 'Character Design', 'Character design'),
  (33, 4, 'Editorial', 'Editorial'),
  (34, 4, 'Environment', 'Environment'),
  (35, 4, 'Food Visuals', 'Food visuals'),
  (36, 4, 'Illustration', 'Illustration'),
  (37, 4, 'Portrait', 'Portrait'),
  (38, 4, 'Produktvisual', 'Product visual'),
  (39, 4, 'Sci-Fi', 'Sci-fi'),
  (40, 4, 'Storyboard', 'Storyboard'),
  (41, 5, 'Branding', 'Branding'),
  (42, 5, 'Business Modell', 'Business model'),
  (43, 5, 'Community', 'Community'),
  (44, 5, 'Content Strategie', 'Content strategy'),
  (45, 5, 'Growth', 'Growth'),
  (46, 5, 'Hooks', 'Hooks'),
  (47, 5, 'Kooperation', 'Collaboration'),
  (48, 5, 'Monetarisierung', 'Monetization'),
  (49, 5, 'Produktivität', 'Productivity'),
  (50, 5, 'Video Storytelling', 'Video storytelling'),
  (51, 6, 'Arbeitszeugnis', 'Reference'),
  (52, 6, 'Bewerbung', 'Application'),
  (53, 6, 'Interview', 'Interview'),
  (54, 6, 'Karrierewechsel', 'Career transition'),
  (55, 6, 'Leadership', 'Leadership'),
  (56, 6, 'Lebenslauf', 'Resume'),
  (57, 6, 'LinkedIn', 'LinkedIn'),
  (58, 6, 'Networking', 'Networking'),
  (59, 6, 'Onboarding', 'Onboarding'),
  (60, 6, 'Verhandlung', 'Negotiation'),
  (61, 7, 'Copywriting', 'Copywriting'),
  (62, 7, 'Funnel', 'Funnel'),
  (63, 7, 'Kampagne', 'Campaign'),
  (64, 7, 'Launch', 'Launch'),
  (65, 7, 'Leadgen', 'Lead generation'),
  (66, 7, 'Messaging', 'Messaging'),
  (67, 7, 'Performance', 'Performance'),
  (68, 7, 'Positionierung', 'Positioning'),
  (69, 7, 'Reporting', 'Reporting'),
  (70, 7, 'Zielgruppe', 'Audience'),
  (71, 8, 'Debatte', 'Debate'),
  (72, 8, 'Entscheidungsgrundlage', 'Decision support'),
  (73, 8, 'Faktenkommunikation', 'Fact communication'),
  (74, 8, 'Kommunalpolitik', 'Municipal policy'),
  (75, 8, 'Krisenkommunikation', 'Crisis communication'),
  (76, 8, 'Moderation', 'Moderation'),
  (77, 8, 'Policy Analyse', 'Policy analysis'),
  (78, 8, 'Positionspapier', 'Position paper'),
  (79, 8, 'Stakeholder', 'Stakeholders'),
  (80, 8, 'Wahlanalyse', 'Election analysis'),
  (81, 9, 'Delegation', 'Delegation'),
  (82, 9, 'Entscheidungen', 'Decisions'),
  (83, 9, 'Fokus', 'Focus'),
  (84, 9, 'Habits', 'Habits'),
  (85, 9, 'Kommunikation', 'Communication'),
  (86, 9, 'Meetings', 'Meetings'),
  (87, 9, 'Priorisierung', 'Prioritization'),
  (88, 9, 'Review', 'Review'),
  (89, 9, 'Routine', 'Routine'),
  (90, 9, 'Zeitmanagement', 'Time management'),
  (91, 10, 'Deutsch', 'Language'),
  (92, 10, 'Lernzettel', 'Study notes'),
  (93, 10, 'Mathematik', 'Math'),
  (94, 10, 'Naturwissenschaft', 'Science'),
  (95, 10, 'Organisation', 'Organization'),
  (96, 10, 'Projektarbeit', 'Project work'),
  (97, 10, 'Prüfungsvorbereitung', 'Exam prep'),
  (98, 10, 'Referat', 'Presentation'),
  (99, 10, 'Schreiben', 'Writing'),
  (100, 10, 'Sprachen', 'Languages'),
  (101, 11, 'Autorität', 'Authority'),
  (102, 11, 'Content Briefing', 'Content briefing'),
  (103, 11, 'Content Pflege', 'Content maintenance'),
  (104, 11, 'Intent Analyse', 'Intent analysis'),
  (105, 11, 'Interne Verlinkung', 'Internal linking'),
  (106, 11, 'Keyword Strategie', 'Keyword strategy'),
  (107, 11, 'Onpage', 'On-page'),
  (108, 11, 'Snippet', 'Snippet'),
  (109, 11, 'Technical SEO', 'Technical SEO'),
  (110, 11, 'Wettbewerb', 'Competitor analysis'),
  (111, 12, 'Analyse', 'Analysis'),
  (112, 12, 'Expose', 'Proposal'),
  (113, 12, 'Forschungsdesign', 'Research design'),
  (114, 12, 'Literaturarbeit', 'Literature'),
  (115, 12, 'Methodik', 'Methodology'),
  (116, 12, 'Prüfung', 'Exam'),
  (117, 12, 'Seminararbeit', 'Term paper'),
  (118, 12, 'Thesis', 'Thesis'),
  (119, 12, 'Wissenschaftliches Schreiben', 'Academic writing'),
  (120, 12, 'Zitation', 'Citation'),
  (121, 13, 'Analytics', 'Analytics'),
  (122, 13, 'Ideenfindung', 'Idea research'),
  (123, 13, 'Monetarisierung', 'Monetization'),
  (124, 13, 'Packaging', 'Packaging'),
  (125, 13, 'Repurposing', 'Repurposing'),
  (126, 13, 'Retention', 'Retention'),
  (127, 13, 'Script', 'Script'),
  (128, 13, 'SEO', 'SEO'),
  (129, 13, 'Serien', 'Series'),
  (130, 13, 'Wachstum', 'Growth')
on conflict (category_id, name_de, name_en) do update set name_de = excluded.name_de, name_en = excluded.name_en;

