do $$
begin
    if exists (
        select 1
        from information_schema.tables
        where table_schema = 'public'
          and table_name = 'PROMPT_presets'
    )
    and exists (
        select 1
        from information_schema.columns
        where table_schema = 'public'
          and table_name = 'PROMPT_presets'
          and column_name = 'category'
    ) then
        alter table public."PROMPT_presets" rename to "PROMPT_presets_legacy";
    end if;
end $$;

create table if not exists public."PROMPT_categories" (
    id integer generated by default as identity primary key,
    code text not null unique
);

create table if not exists public."PROMPT_main_categories" (
    id integer generated by default as identity primary key,
    code text not null unique
);

create table if not exists public."PROMPT_platforms" (
    id integer generated by default as identity primary key,
    name text not null unique
);

create table if not exists public."PROMPT_tones" (
    id integer generated by default as identity primary key,
    code text not null unique
);

create table if not exists public."PROMPT_lengths" (
    id integer generated by default as identity primary key,
    code text not null unique
);

create table if not exists public."PROMPT_output_formats" (
    id integer generated by default as identity primary key,
    code text not null unique
);

create table if not exists public."PROMPT_complexity_levels" (
    id integer generated by default as identity primary key,
    code text not null unique
);

create table if not exists public."PROMPT_subcategories" (
    id integer generated by default as identity primary key,
    category_id integer not null references public."PROMPT_categories" (id) on delete cascade,
    name_de text not null,
    name_en text not null,
    constraint prompt_subcategories_unique unique (category_id, name_de, name_en)
);

create table if not exists public."PROMPT_tags" (
    id integer generated by default as identity primary key,
    language_code text not null check (language_code in ('de', 'en')),
    value text not null,
    normalized_value text generated always as (lower(value)) stored,
    constraint prompt_tags_unique unique (language_code, normalized_value)
);

create table if not exists public."PROMPT_presets" (
    id text primary key,
    slug text not null unique,
    category_id integer not null references public."PROMPT_categories" (id),
    subcategory_id integer not null references public."PROMPT_subcategories" (id),
    main_category_id integer not null references public."PROMPT_main_categories" (id),
    platform_id integer not null references public."PROMPT_platforms" (id),
    tone_id integer not null references public."PROMPT_tones" (id),
    length_id integer not null references public."PROMPT_lengths" (id),
    output_format_id integer not null references public."PROMPT_output_formats" (id),
    complexity_level_id integer not null references public."PROMPT_complexity_levels" (id),
    title_de text not null,
    title_en text not null,
    description_de text not null,
    description_en text not null,
    popularity_score integer not null,
    example_input_de text not null,
    example_input_en text not null,
    example_prompt_de text not null,
    example_prompt_en text not null,
    default_topic_de text not null,
    default_topic_en text not null,
    default_target_audience_de text not null,
    default_target_audience_en text not null,
    default_role_de text not null,
    default_role_en text not null,
    default_extra_instructions_de text not null,
    default_extra_instructions_en text not null,
    is_generated boolean not null default true,
    created_at timestamptz not null default timezone('utc', now()),
    updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public."PROMPT_preset_tags" (
    preset_id text not null references public."PROMPT_presets" (id) on delete cascade,
    tag_id integer not null references public."PROMPT_tags" (id) on delete cascade,
    language_code text not null check (language_code in ('de', 'en')),
    sort_order smallint not null,
    primary key (preset_id, tag_id),
    constraint prompt_preset_tags_order_unique unique (preset_id, language_code, sort_order)
);

create index if not exists idx_prompt_presets_category_id on public."PROMPT_presets" (category_id);
create index if not exists idx_prompt_presets_main_category_id on public."PROMPT_presets" (main_category_id);
create index if not exists idx_prompt_presets_subcategory_id on public."PROMPT_presets" (subcategory_id);
create index if not exists idx_prompt_presets_platform_id on public."PROMPT_presets" (platform_id);
create index if not exists idx_prompt_presets_popularity on public."PROMPT_presets" (popularity_score desc);
create index if not exists idx_prompt_subcategories_category_id on public."PROMPT_subcategories" (category_id);
create index if not exists idx_prompt_tags_language_code on public."PROMPT_tags" (language_code);
create index if not exists idx_prompt_preset_tags_tag_id on public."PROMPT_preset_tags" (tag_id);
create index if not exists idx_prompt_preset_tags_language_order on public."PROMPT_preset_tags" (language_code, sort_order);

do $$
begin
    if exists (
        select 1
        from information_schema.tables
        where table_schema = 'public'
          and table_name = 'PROMPT_presets_legacy'
    ) then
        insert into public."PROMPT_categories" (code)
        select distinct legacy.category
        from public."PROMPT_presets_legacy" legacy
        on conflict (code) do nothing;

        insert into public."PROMPT_main_categories" (code)
        select distinct legacy.default_main_category
        from public."PROMPT_presets_legacy" legacy
        on conflict (code) do nothing;

        insert into public."PROMPT_platforms" (name)
        select distinct legacy.default_platform
        from public."PROMPT_presets_legacy" legacy
        on conflict (name) do nothing;

        insert into public."PROMPT_tones" (code)
        select distinct legacy.default_tone
        from public."PROMPT_presets_legacy" legacy
        on conflict (code) do nothing;

        insert into public."PROMPT_lengths" (code)
        select distinct legacy.default_length
        from public."PROMPT_presets_legacy" legacy
        on conflict (code) do nothing;

        insert into public."PROMPT_output_formats" (code)
        select distinct legacy.default_output_format
        from public."PROMPT_presets_legacy" legacy
        on conflict (code) do nothing;

        insert into public."PROMPT_complexity_levels" (code)
        select distinct legacy.default_complexity_level
        from public."PROMPT_presets_legacy" legacy
        on conflict (code) do nothing;

        insert into public."PROMPT_subcategories" (category_id, name_de, name_en)
        select distinct category_lookup.id, legacy.subcategory_de, legacy.subcategory_en
        from public."PROMPT_presets_legacy" legacy
        join public."PROMPT_categories" category_lookup
          on category_lookup.code = legacy.category
        on conflict (category_id, name_de, name_en) do nothing;

        insert into public."PROMPT_tags" (language_code, value)
        select distinct 'de', tag_value.value
        from public."PROMPT_presets_legacy" legacy
        cross join lateral unnest(legacy.tags_de) as tag_value(value)
        on conflict (language_code, normalized_value) do nothing;

        insert into public."PROMPT_tags" (language_code, value)
        select distinct 'en', tag_value.value
        from public."PROMPT_presets_legacy" legacy
        cross join lateral unnest(legacy.tags_en) as tag_value(value)
        on conflict (language_code, normalized_value) do nothing;

        insert into public."PROMPT_presets" (
            id,
            slug,
            category_id,
            subcategory_id,
            main_category_id,
            platform_id,
            tone_id,
            length_id,
            output_format_id,
            complexity_level_id,
            title_de,
            title_en,
            description_de,
            description_en,
            popularity_score,
            example_input_de,
            example_input_en,
            example_prompt_de,
            example_prompt_en,
            default_topic_de,
            default_topic_en,
            default_target_audience_de,
            default_target_audience_en,
            default_role_de,
            default_role_en,
            default_extra_instructions_de,
            default_extra_instructions_en,
            is_generated,
            created_at,
            updated_at
        )
        select
            legacy.id,
            legacy.slug,
            category_lookup.id,
            subcategory_lookup.id,
            main_category_lookup.id,
            platform_lookup.id,
            tone_lookup.id,
            length_lookup.id,
            output_format_lookup.id,
            complexity_lookup.id,
            legacy.title_de,
            legacy.title_en,
            legacy.description_de,
            legacy.description_en,
            legacy.popularity_score,
            legacy.example_input_de,
            legacy.example_input_en,
            legacy.example_prompt_de,
            legacy.example_prompt_en,
            legacy.default_topic_de,
            legacy.default_topic_en,
            legacy.default_target_audience_de,
            legacy.default_target_audience_en,
            legacy.default_role_de,
            legacy.default_role_en,
            legacy.default_extra_instructions_de,
            legacy.default_extra_instructions_en,
            legacy.is_generated,
            legacy.created_at,
            legacy.updated_at
        from public."PROMPT_presets_legacy" legacy
        join public."PROMPT_categories" category_lookup
          on category_lookup.code = legacy.category
        join public."PROMPT_subcategories" subcategory_lookup
          on subcategory_lookup.category_id = category_lookup.id
         and subcategory_lookup.name_de = legacy.subcategory_de
         and subcategory_lookup.name_en = legacy.subcategory_en
        join public."PROMPT_main_categories" main_category_lookup
          on main_category_lookup.code = legacy.default_main_category
        join public."PROMPT_platforms" platform_lookup
          on platform_lookup.name = legacy.default_platform
        join public."PROMPT_tones" tone_lookup
          on tone_lookup.code = legacy.default_tone
        join public."PROMPT_lengths" length_lookup
          on length_lookup.code = legacy.default_length
        join public."PROMPT_output_formats" output_format_lookup
          on output_format_lookup.code = legacy.default_output_format
        join public."PROMPT_complexity_levels" complexity_lookup
          on complexity_lookup.code = legacy.default_complexity_level
        on conflict (id) do update set
            slug = excluded.slug,
            category_id = excluded.category_id,
            subcategory_id = excluded.subcategory_id,
            main_category_id = excluded.main_category_id,
            platform_id = excluded.platform_id,
            tone_id = excluded.tone_id,
            length_id = excluded.length_id,
            output_format_id = excluded.output_format_id,
            complexity_level_id = excluded.complexity_level_id,
            title_de = excluded.title_de,
            title_en = excluded.title_en,
            description_de = excluded.description_de,
            description_en = excluded.description_en,
            popularity_score = excluded.popularity_score,
            example_input_de = excluded.example_input_de,
            example_input_en = excluded.example_input_en,
            example_prompt_de = excluded.example_prompt_de,
            example_prompt_en = excluded.example_prompt_en,
            default_topic_de = excluded.default_topic_de,
            default_topic_en = excluded.default_topic_en,
            default_target_audience_de = excluded.default_target_audience_de,
            default_target_audience_en = excluded.default_target_audience_en,
            default_role_de = excluded.default_role_de,
            default_role_en = excluded.default_role_en,
            default_extra_instructions_de = excluded.default_extra_instructions_de,
            default_extra_instructions_en = excluded.default_extra_instructions_en,
            is_generated = excluded.is_generated,
            updated_at = timezone('utc', now());

        insert into public."PROMPT_preset_tags" (preset_id, tag_id, language_code, sort_order)
        select
            legacy.id,
            tag_lookup.id,
            'de',
            tag_value.sort_order::smallint
        from public."PROMPT_presets_legacy" legacy
        cross join lateral unnest(legacy.tags_de) with ordinality as tag_value(value, sort_order)
        join public."PROMPT_tags" tag_lookup
          on tag_lookup.language_code = 'de'
         and tag_lookup.normalized_value = lower(tag_value.value)
        on conflict (preset_id, tag_id) do update set
            language_code = excluded.language_code,
            sort_order = excluded.sort_order;

        insert into public."PROMPT_preset_tags" (preset_id, tag_id, language_code, sort_order)
        select
            legacy.id,
            tag_lookup.id,
            'en',
            tag_value.sort_order::smallint
        from public."PROMPT_presets_legacy" legacy
        cross join lateral unnest(legacy.tags_en) with ordinality as tag_value(value, sort_order)
        join public."PROMPT_tags" tag_lookup
          on tag_lookup.language_code = 'en'
         and tag_lookup.normalized_value = lower(tag_value.value)
        on conflict (preset_id, tag_id) do update set
            language_code = excluded.language_code,
            sort_order = excluded.sort_order;
    end if;
end $$;

drop view if exists public."PROMPT_preset_catalog_flat";

create view public."PROMPT_preset_catalog_flat" as
select
    preset.id,
    preset.slug,
    category_lookup.code as category,
    preset.title_de,
    preset.title_en,
    preset.description_de,
    preset.description_en,
    subcategory_lookup.name_de as subcategory_de,
    subcategory_lookup.name_en as subcategory_en,
    coalesce(array_agg(tag_lookup.value order by preset_tag.sort_order) filter (where preset_tag.language_code = 'de'), array[]::text[]) as tags_de,
    coalesce(array_agg(tag_lookup.value order by preset_tag.sort_order) filter (where preset_tag.language_code = 'en'), array[]::text[]) as tags_en,
    preset.popularity_score,
    preset.example_input_de,
    preset.example_input_en,
    preset.example_prompt_de,
    preset.example_prompt_en,
    main_category_lookup.code as default_main_category,
    preset.default_topic_de,
    preset.default_topic_en,
    subcategory_lookup.name_de as default_subcategory_de,
    subcategory_lookup.name_en as default_subcategory_en,
    platform_lookup.name as default_platform,
    preset.default_target_audience_de,
    preset.default_target_audience_en,
    preset.default_role_de,
    preset.default_role_en,
    preset.default_extra_instructions_de,
    preset.default_extra_instructions_en,
    tone_lookup.code as default_tone,
    length_lookup.code as default_length,
    output_format_lookup.code as default_output_format,
    complexity_lookup.code as default_complexity_level,
    preset.is_generated,
    preset.created_at,
    preset.updated_at
from public."PROMPT_presets" preset
join public."PROMPT_categories" category_lookup on category_lookup.id = preset.category_id
join public."PROMPT_subcategories" subcategory_lookup on subcategory_lookup.id = preset.subcategory_id
join public."PROMPT_main_categories" main_category_lookup on main_category_lookup.id = preset.main_category_id
join public."PROMPT_platforms" platform_lookup on platform_lookup.id = preset.platform_id
join public."PROMPT_tones" tone_lookup on tone_lookup.id = preset.tone_id
join public."PROMPT_lengths" length_lookup on length_lookup.id = preset.length_id
join public."PROMPT_output_formats" output_format_lookup on output_format_lookup.id = preset.output_format_id
join public."PROMPT_complexity_levels" complexity_lookup on complexity_lookup.id = preset.complexity_level_id
left join public."PROMPT_preset_tags" preset_tag on preset_tag.preset_id = preset.id
left join public."PROMPT_tags" tag_lookup on tag_lookup.id = preset_tag.tag_id
group by
    preset.id,
    preset.slug,
    category_lookup.code,
    preset.title_de,
    preset.title_en,
    preset.description_de,
    preset.description_en,
    subcategory_lookup.name_de,
    subcategory_lookup.name_en,
    preset.popularity_score,
    preset.example_input_de,
    preset.example_input_en,
    preset.example_prompt_de,
    preset.example_prompt_en,
    main_category_lookup.code,
    preset.default_topic_de,
    preset.default_topic_en,
    platform_lookup.name,
    preset.default_target_audience_de,
    preset.default_target_audience_en,
    preset.default_role_de,
    preset.default_role_en,
    preset.default_extra_instructions_de,
    preset.default_extra_instructions_en,
    tone_lookup.code,
    length_lookup.code,
    output_format_lookup.code,
    complexity_lookup.code,
    preset.is_generated,
    preset.created_at,
    preset.updated_at;

do $$
declare
    table_name text;
    policy_name text;
    prompt_tables text[] := array[
        'PROMPT_categories',
        'PROMPT_main_categories',
        'PROMPT_platforms',
        'PROMPT_tones',
        'PROMPT_lengths',
        'PROMPT_output_formats',
        'PROMPT_complexity_levels',
        'PROMPT_subcategories',
        'PROMPT_tags',
        'PROMPT_presets',
        'PROMPT_preset_tags'
    ];
begin
    foreach table_name in array prompt_tables loop
        execute format('alter table public.%I enable row level security', table_name);
        execute format('grant select on public.%I to anon, authenticated', table_name);

        policy_name := table_name || '_select_public';
        if not exists (
            select 1
            from pg_policies
            where schemaname = 'public'
              and tablename = table_name
              and policyname = policy_name
        ) then
            execute format(
                'create policy %I on public.%I for select to anon, authenticated using (true)',
                policy_name,
                table_name);
        end if;
    end loop;
end $$;

grant select on public."PROMPT_preset_catalog_flat" to anon, authenticated;

comment on table public."PROMPT_presets" is 'Normalized prompt preset catalog.';
comment on view public."PROMPT_preset_catalog_flat" is 'Flattened read-model over the normalized prompt preset catalog.';

drop table if exists public."PROMPT_presets_legacy";
